name: Continuous Integration

env:
  TF_VERSION: 0.12.24
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MY_JSON_ARRAY: '{ "repos": [
    "daspn/actions-test@master", "owner/repo@branch"
  ]}'

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'master'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform init
      run: terraform init

    - name: "Terraform plan"
      run: terraform plan

    - name: "Array test"
      run: |
        echo jq -r .repos <<< '${{ env.MY_JSON_ARRAY }}'
