name: Continuous Integration

env:
  TF_VERSION: 0.12.24
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'master'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Private actions checkout
      uses: daspn/private-actions-checkout@master
      with:
        actions_list: '["getzoop/actions-message-service@v1", "getzoop/actions-deployment-gate@v1"]'
        actions_base_path: ${{ github.workspace }}/.github/actions

    - name: Private actions checkout validation
      run: |
        ls -lR ${{ github.workspace }}/.github/actions

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform init
      run: terraform init

    - name: "Terraform plan"
      run: terraform plan
